[project]
name = "ai-micro-project-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "json-repair>=0.50.0",
    "langfuse==2.59.7",
    "litellm[caching]>=1.76.2",
    "omegaconf>=2.3.0",
    "pydantic>=2.11.7",
    "rich>=14.1.0",
    "tenacity>=9.1.2",
    "tiktoken>=0.11.0",
    "typer>=0.17.3",
    "fastapi>=0.112.0",
    "uvicorn[standard]>=0.30.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
aipg = "aipg:main"
api = "aipg.server:main"

[dependency-groups]
dev = [
    "mypy>=1.17.1",
    "ruff>=0.12.12",
]

[tool.hatch.build.targets.wheel]
packages = ["aipg"]

[tool.hatch.build.targets.sdist]
include = ["aipg", "README.md", "pyproject.toml"]
