name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install dev deps
        run: uv sync --group dev

      - name: Run pre-commit (all files)
        run: uv run pre-commit run --all-files

  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install project
        run: uv sync --group dev

      - name: Run pytest (unit only)
        env:
          PYTEST_ADDOPTS: "-m 'not integration'"
        run: uv run pytest -q

name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  python:
    name: Python lint, format check, and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup uv
        uses: astral-sh/setup-uv@v4

      - name: Sync dependencies (all groups)
        run: uv sync --all-groups

      - name: Ruff lint
        run: uv run ruff check --output-format=github .

      - name: Ruff format check
        run: uv run ruff format --check .

      - name: Run tests
        run: uv run pytest

